run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters (errcheck disabled due to 75+ issues)
    - gosimple          # Simplify code
    - govet             # Vet examines Go source code
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Advanced Go linter
    - unused            # Check for unused code

    # Additional linters
    - asciicheck        # Check for non-ASCII identifiers
    - bodyclose         # Check HTTP response body is closed
    - dogsled           # Check for too many blank identifiers
    - durationcheck     # Check for multiplying time.Duration
    - errorlint         # Check for error wrapping issues
    # - exhaustive        # Check exhaustiveness of enum switch (disabled - too strict)
    - copyloopvar       # Check for pointers to loop variables (renamed from exportloopref)
    - gci               # Control Go package import order
    # - gochecknoinits    # Check for init functions (disabled - legitimate uses)
    # - gocognit          # Compute cognitive complexities (disabled - requires refactoring)
    # - goconst           # Find repeated strings that could be constants (disabled - too strict)
    # - gocritic          # Provides diagnostics that check for bugs (disabled - requires refactoring)
    # - gocyclo           # Compute cyclomatic complexities (disabled - requires refactoring)
    # - godot             # Check if comments end in a period (disabled - too many existing comments without periods)
    - gofmt             # Check if code was formatted with gofmt
    - goimports         # Check import statements are formatted
    # - mnd               # Detect magic numbers (disabled - too strict for HTTP codes/timeouts)
    - goprintffuncname  # Check printf function names
    - gosec             # Inspect for security problems
    # - lll               # Report long lines (disabled - too strict for SQL queries)
    - misspell          # Find misspelled English words
    - nakedret          # Find naked returns in functions
    # - nestif            # Report deeply nested if statements (disabled - requires refactoring)
    - nilerr            # Find code returning nil even if it checks err
    # - revive            # Fast, configurable, extensible linter (disabled - too many issues)
    - rowserrcheck      # Check whether Err of rows is checked
    - sqlclosecheck     # Check that sql.Rows and sql.Stmt are closed
    # - stylecheck        # Replacement for golint (disabled - too strict)
    - tparallel         # Detect inappropriate usage of t.Parallel()
    - unconvert         # Remove unnecessary type conversions
    # - unparam           # Report unused function parameters (disabled - interface compliance issues)
    - wastedassign      # Find wasted assignment statements
    - whitespace        # Detect leading and trailing whitespace

  disable:
    - funlen            # Checks function length (too strict)
    - gochecknoglobals  # Checks no global variables (too strict)
    - godox             # Detect FIXME, TODO comments (noisy)
    - err113            # Enforce error wrapping (renamed from goerr113)
    - wrapcheck         # Check error wrapping (too strict)
    - dupl              # Duplicate code detection (too strict, legitimate pattern reuse)
    - nlreturn          # Newline before return (too strict)
    - noctx             # HTTP context usage (requires refactoring)
    - prealloc          # Slice preallocation (minor optimization)
    - thelper           # Test helper t.Helper() (requires refactoring)
    - predeclared       # Shadowing predeclared identifiers (too strict)
    - errcheck          # Error checking (75+ issues, needs dedicated refactoring)
    - mnd               # Magic numbers (too strict for HTTP codes/timeouts)
    - nestif            # Nested if complexity (requires refactoring)
    - unparam           # Unused params (interface compliance issues)
    - lll               # Line length (too strict for SQL queries)
    - gochecknoinits    # Init functions (legitimate uses)

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Struct field alignment optimization (minor, noisy)
      - shadow          # Already covered by check-shadowing deprecation

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 140
    tab-width: 4

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 4

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File path from variable (needed for config files)
      - G107  # Potential HTTP request made with variable url (OAuth discovery URLs)
      - G115  # Integer overflow conversion (pool config values are validated)
      - G101  # Potential hardcoded credentials (dev defaults with clear comment)

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/waffles/waffles)
    skip-generated: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - goconst
        - mnd
        - revive
        - unparam
        - govet
        - unused

    # Exclude test/ directory (fixtures, e2e, cmd tools, etc.)
    - path: test/
      linters:
        - errcheck
        - gosec
        - dupl
        - mnd
        - godot
        - nlreturn
        - gocyclo
        - gocognit
        - gocritic
        - goconst
        - revive
        - govet

    # Allow embed declarations
    - linters:
        - typecheck
      text: "embed"

    # Allow NopLogger to have unused ctx (implements interface)
    - path: pkg/logger/nop\.go
      linters:
        - revive
      text: "unused-parameter"

    # Allow MCPError name (changing it breaks API compatibility)
    - path: pkg/mcp/errors\.go
      linters:
        - revive
      text: "stutters"

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show all issues from a linter
  new: false

  # Fix issues if possible
  fix: false
