# YAML Lint configuration
extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable  # Allow documented examples with different indentation
  indentation:
    spaces: 2
    indent-sequences: consistent
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  node_modules/
  web-app/node_modules/
  .git/
  vendor/
